### ISSUE TITLE
Identify Breakfast Recipe

### ISSUE THREAD

**Issue by danielpmahoney** [IntroToCode/CodeMates5_Fall22#1]
## 💬 Discussion topic

We need to come up with a breakfast item!

## ❗ Potential issues

We might not agree on the best breakfast recipe to use

## 👥 People to consult

@bpicciano for recipe

## 📃 Details

@bpicciano - Find recipe online & share link in Slack, Fill in recipe name & servings, Submit pull request for review by @willmckelvey & @mikahyden, After review, @willmckelvey will merge 

@willmckelvey - Fill in time to prepare, ingredients, Submit pull request for review by @mikahyden & @danielpmahoney, After review, @mikahyden will merge

@mikahyden - Fill in equipment needed, Submit pull request for review by @danielpmahoney & @abianesucb, After review, @danielpmahoney will merge

@danielpmahoney - Fill in steps for preparation, Submit pull request for review by @abianesucb & @bpicciano, After review, @abianesucb will merge

@abianesucb - Fill in notes & codemates, Submit pull request for review by @bpicciano & @willmckelvey, After review, @bpicciano will merge

**Comment by abianesucb** [comment]
Updated 10/22/22 to expand on acceptance criteria and delineation of work

**Comment by bpicciano** [comment]
Propose recipe to use is here (Blackberry stuffed french toast): https://cooking.nytimes.com/recipes/1021243-blackberry-stuffed-french-toast?ds_c=71700000052595478&gclid=CjwKCAjw79iaBhAJEiwAPYwoCJRst5CmEYaVIbPDGh_zAL-QT2diZ8AZugp0SCTV-4c6YFNiruKLuRoC3esQAvD_BwE&gclsrc=aw.ds

**Comment by bpicciano** [comment]
I think I screwed up below where I created a new branch called "Blackberry Stuffed French Toast" . I think you all should propose pull requests to the main branch readme in the Breakfast folder (not propose changes to the "Blackberry Stuffed French Toast" branch?)  @willmckelvey does that sound right? 

[wrong, I think]: "I created a new branch within our Codemates 5 repository for the Breakfast recipe, and made a commit with title and # servings: https://github.com/IntroToCode/CodeMates5_Fall22/tree/Blackberry-Stuffed-French-Toast"

**Comment by abianesucb** [comment]
We finished the recipe!
